# ============================================================
# HidroControl-3
# Laboratório MQTT — Broker Privado
#
# Fase inicial:
# - MQTT sem TLS
# - Sem autenticação
# - Sem ACL ativa
# - Sem bridge
# - Sem persistência
# ============================================================

# Porta exclusiva do Broker Privado no laboratório.
listener 1884 0.0.0.0

# Permitido somente durante a fase inicial de validação.
allow_anonymous true

# Será ativada em etapa posterior.
persistence false

# Logs enviados ao terminal.
log_dest stdout
log_type all

# Registra conexões e desconexões.
connection_messages true
