# ============================================================
# HidroControl-3
# Laboratório MQTT — Broker Público
#
# Fase inicial:
# - MQTT sem TLS
# - Sem autenticação
# - Sem ACL
# - Sem bridge
# ============================================================

# Porta MQTT utilizada pelo Broker Público no laboratório.
listener 1883 0.0.0.0

# Acesso anônimo permitido somente nesta fase inicial.
allow_anonymous true

# Persistência desativada temporariamente.
persistence false

# Logs enviados ao terminal.
log_dest stdout

# Exibe todos os tipos de mensagens no laboratório.
log_type all

# Registra conexões e desconexões.
connection_messages true
