# ============================================================
# HIDROCONTROL-3 — BROKER MQTT PRIVADO
#
# Projeto oficial:
# /home/renato/HidroControl-3
#
# FASE 1:
# Broker privado local, ainda SEM bridge com HiveMQ Cloud.
# ============================================================

listener 1884 127.0.0.1
protocol mqtt

# ------------------------------------------------------------
# AUTENTICACAO
# ------------------------------------------------------------

allow_anonymous false

password_file /home/renato/HidroControl-3/mqtt/privado/passwd


# ------------------------------------------------------------
# PERSISTENCIA
# ------------------------------------------------------------

persistence true

persistence_location /home/renato/HidroControl-3/mqtt/privado/persistence/


# ------------------------------------------------------------
# LOG
# ------------------------------------------------------------

log_dest stdout

log_type error
log_type warning
log_type notice
log_type information

connection_messages true

# ============================================================
# BRIDGE TLS — HIVEMQ CLOUD -> BROKER PRIVADO
# ============================================================

connection hivemq-cloud-para-privado

address 3f64e3d334e045448a9277d405a8f0da.s1.eu.hivemq.cloud:8883

remote_clientid hidrocontrol-bridge-notemint
remote_username hidrocontrol-bridge
remote_password Camila12@

bridge_protocol_version mqttv311
try_private false

bridge_cafile /etc/ssl/certs/ca-certificates.crt
bridge_tls_version tlsv1.2
bridge_insecure false

start_type automatic
restart_timeout 10
cleansession true
notifications false

topic hidrocontrol/ac220-000110/telemetry in 1
topic hidrocontrol/ac220-000110/modo out 1
